services:
    db:
        image: mysql:5.7
        container_name: my_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rlt
            MYSQL_USER: u
            MYSQL_PASSWORD: u
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql # <-- Corrected syntax

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root

    web:
        image: php:7.4-apache
        container_name: my_apache
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db

volumes:
    db_data:
